name: example
description: Fleasy examples

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fleasy:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.15.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
