include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - cancel_subscriptions
    - cascade_invocations
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - non_constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_typing_uninitialized_variables
    - sort_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_statements