name: fleasy
description: Useful and easy to use extensions, helper classes and widgets to create Flutter apps easier.
version: 0.15.1
repository: https://github.com/devj3ns/fleasy
issue_tracker: https://github.com/devj3ns/fleasy/issues

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  flash: ^3.1.0
  flutter_lints: ^3.0.2

dev_dependencies:
  test: ^1.22.2