name: fleasy
description: Useful and easy to use extensions, helper classes and widgets to create Flutter apps easier.
version: 0.3.2
repository: https://github.com/devj3ns/fleasy
issue_tracker: https://github.com/devj3ns/fleasy/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  universal_platform: ^1.0.0+1
  font_awesome_flutter: ^9.1.0
  flash: ^2.0.1
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.0.1

dev_dependencies:
  test: ^1.17.9