name: fleasy
description: Useful and easy to use extensions, helper classes and widgets to help creating Flutter apps easier.
version: 1.0.0
repository: https://github.com/devj3ns/fleasy
authors:
  - Jens Becker - jensbecker.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  universal_platform: ^1.0.0-nullsafety
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  test: ^1.17.8
  flutter_lints: ^1.0.3
  dart_code_metrics: ^4.0.0


