name: fleasy
description: Useful and easy to use extensions, helper classes and widgets to create Flutter apps easier.
version: 0.10.0
repository: https://github.com/devj3ns/fleasy
issue_tracker: https://github.com/devj3ns/fleasy/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  flash: ^2.0.3+2
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.10.0

dev_dependencies:
  test: ^1.17.9