name: fleasy
description: Useful and easy to use extensions, helper classes and widgets to create Flutter apps easier.
version: 0.17.0
repository: https://github.com/devj3ns/fleasy
issue_tracker: https://github.com/devj3ns/fleasy/issues

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ">=0.19.0 <=0.20.2"
  font_awesome_flutter: ^10.8.0
  flash: ^3.1.1
  flutter_lints: ^5.0.0

dev_dependencies:
  test: ^1.25.15