name: fleasy
description: Useful and easy to use extensions, helper classes and widgets to create Flutter apps easier.
version: 0.13.0
repository: https://github.com/devj3ns/fleasy
issue_tracker: https://github.com/devj3ns/fleasy/issues

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  font_awesome_flutter: ^10.1.0
  flash: ^2.0.3+2
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2 # Does not work with dart 2.17.0, see https://github.com/dart-lang/sdk/issues/48682

dev_dependencies:
  test: ^1.20.1