name: fleasy
description: Useful and easy to use extensions, helper classes and widgets to create Flutter apps easier.
version: 0.14.1
repository: https://github.com/devj3ns/fleasy
issue_tracker: https://github.com/devj3ns/fleasy/issues

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  font_awesome_flutter: ^10.3.0
  flash: ^2.0.5
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.5.1

dev_dependencies:
  test: ^1.22.2