name: flutter_extensions
description: Some Flutter/Dart extensions which I need very often :)
version: 1.0.0
repository: https://github.com/devj3ns/flutter_extensions

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.0

