name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
      - 'example/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
      - 'example/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
